name: CI

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 2

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks with Custom Config
        id: gitleaks  # assign an ID to the step for later reference
        continue-on-error: true  # allow the workflow to continue even if Gitleaks finds leaks
        run: |
          set -e
          GITLEAKS_VERSION=$(curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest | grep tag_name | cut -d '"' -f4)
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION#v}_linux_x64.tar.gz -o gitleaks.tar.gz
          tar -xzf gitleaks.tar.gz gitleaks
          chmod +x gitleaks
          ./gitleaks detect \
            --source . \
            --config .gitleaks.toml \
            --no-git \
            --exit-code 1 \
            --report-format=json \
            --report-path=gitleaks-report.json
          echo "exit_code=$?" >> $GITHUB_OUTPUT     
        # capture the exit code for later use

      - name: Upload Gitleaks Report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json

      - name: Fail if Gitleaks Found Leaks
        if: steps.gitleaks.outputs.exit_code == '1'
        # check if Gitleaks found leaks
        run: exit 1

        #configure-aws-credentials workflow for OIDC role assumption and export AWS creds to environment
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="admin_username=$ADMIN_USERNAME" \
            -var="admin_password=$ADMIN_PASSWORD" \
            -var="oidc_role_arn=${{ secrets.OIDC_ROLE_ARN }}"
#        - name: ADMIN_PASSWORD and ADMIN_USERNAME are for EC2 instance admin user